[AnnounceStrengthForceLevel.AlertWatcherActor]
; Polling Rate at geoscape for Advent Strength and Force Level changes, in seconds.
; Lowering this value shortens the average time between the increase in Advent Strength or Force Level and the notification (or geoscape pause) from this mod.
; However setting this value too low might cause lags in geoscape.
; Lowest value is 0.1 sec - lower values will be forced to 0.1
fPollingRate = 0.5