class UIS_MCM extends Object config(AnnounceStrengthForceLevel_MCM);

`include(AnnounceStrengthForceLevel\Src\AnnounceStrengthForceLevel\MCM_API_Includes.uci)
`include(AnnounceStrengthForceLevel\Src\AnnounceStrengthForceLevel\MCM_API_CfgHelpers.uci)
`include(AnnounceStrengthForceLevel\Src\AnnounceStrengthForceLevel\LoggerMacros.uci)

var config int CONFIG_VERSION;

/*
var config bool NOTIFY_ADVENT_STRENGTH, NOTIFY_FORCE_LEVEL, PAUSE_ADVENT_STRENGTH, PAUSE_FORCE_LEVEL;
var config int	MIN_ADVENT_STRENGTH_PAUSE, MIN_FORCE_LEVEL_PAUSE;
var config bool ADVENT_STRENGTH_PAUSE_REGION_0, ADVENT_STRENGTH_PAUSE_REGION_1, ADVENT_STRENGTH_PAUSE_REGION_2, ADVENT_STRENGTH_PAUSE_REGION_3, ADVENT_STRENGTH_PAUSE_REGION_4, ADVENT_STRENGTH_PAUSE_REGION_5, ADVENT_STRENGTH_PAUSE_REGION_6, ADVENT_STRENGTH_PAUSE_REGION_7, ADVENT_STRENGTH_PAUSE_REGION_8, ADVENT_STRENGTH_PAUSE_REGION_9, ADVENT_STRENGTH_PAUSE_REGION_10, ADVENT_STRENGTH_PAUSE_REGION_11, ADVENT_STRENGTH_PAUSE_REGION_12, ADVENT_STRENGTH_PAUSE_REGION_13, ADVENT_STRENGTH_PAUSE_REGION_14, ADVENT_STRENGTH_PAUSE_REGION_15;
*/

`MCM_API_AutoCheckBoxVars(NOTIFY_ADVENT_STRENGTH);
`MCM_API_AutoCheckBoxVars(NOTIFY_FORCE_LEVEL);
`MCM_API_AutoCheckBoxVars(PAUSE_ADVENT_STRENGTH);
`MCM_API_AutoCheckBoxVars(PAUSE_FORCE_LEVEL);

`MCM_API_AutoSliderVars(MIN_ADVENT_STRENGTH_PAUSE);
`MCM_API_AutoSliderVars(MIN_FORCE_LEVEL_PAUSE);

`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_0);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_1);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_2);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_3);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_4);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_5);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_6);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_7);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_8);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_9);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_10);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_11);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_12);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_13);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_14);
`MCM_API_AutoCheckBoxVars(ADVENT_STRENGTH_PAUSE_REGION_15);

var localized string sModName, sGeneralSettings_MCMText, sRegionalSettings_MCMText;//, NOTIFY_ADVENT_STRENGTH_MCMText, NOTIFY_FORCE_LEVEL_MCMText, PAUSE_ADVENT_STRENGTH_MCMText, PAUSE_FORCE_LEVEL_MCMText, MIN_ADVENT_STRENGTH_PAUSE_MCMText, MIN_FORCE_LEVEL_PAUSE_MCMText, ADVENT_STRENGTH_PAUSE_REGIONS_MCMText;

/*
var MCM_API_Checkbox NOTIFY_ADVENT_STRENGTH_MCMUI, NOTIFY_FORCE_LEVEL_MCMUI, PAUSE_ADVENT_STRENGTH_MCMUI, PAUSE_FORCE_LEVEL_MCMUI;
var MCM_API_Slider MIN_ADVENT_STRENGTH_PAUSE_MCMUI, MIN_FORCE_LEVEL_PAUSE_MCMUI;
var MCM_API_Checkbox ADVENT_STRENGTH_PAUSE_REGION_0_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_1_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_2_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_3_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_4_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_5_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_6_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_7_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_8_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_9_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_10_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_11_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_12_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_13_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_14_MCMUI, ADVENT_STRENGTH_PAUSE_REGION_15_MCMUI;
*/

event OnInit(UIScreen Screen)
{
	`MCM_API_Register(Screen, ClientModCallback);
}

`MCM_CH_VersionChecker(class'MCM_Defaults'.default.VERSION,CONFIG_VERSION)

`MCM_API_AutoCheckBoxSaveHandler(NOTIFY_ADVENT_STRENGTH);
`MCM_API_AutoCheckBoxSaveHandler(NOTIFY_FORCE_LEVEL);
`MCM_API_AutoCheckBoxSaveHandler(PAUSE_ADVENT_STRENGTH);
`MCM_API_AutoCheckBoxSaveHandler(PAUSE_FORCE_LEVEL);
`MCM_API_AutoSliderSaveHandler(MIN_ADVENT_STRENGTH_PAUSE);
`MCM_API_AutoSliderSaveHandler(MIN_FORCE_LEVEL_PAUSE);

`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_0);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_1);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_2);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_3);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_4);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_5);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_6);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_7);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_8);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_9);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_10);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_11);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_12);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_13);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_14);
`MCM_API_AutoCheckBoxSaveHandler(ADVENT_STRENGTH_PAUSE_REGION_15);

simulated function PauseAdventStrengthChangeHandler(MCM_API_Setting _, bool Value)
{
	`TRACE_ENTRY("");
	MIN_ADVENT_STRENGTH_PAUSE_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_0_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_1_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_2_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_3_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_4_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_5_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_6_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_7_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_8_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_9_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_10_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_11_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_12_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_13_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_14_MCMUI.SetEditable(Value);
	ADVENT_STRENGTH_PAUSE_REGION_15_MCMUI.SetEditable(Value);
	`TRACE_EXIT("");
}

simulated function PauseForceLevelChangeHandler(MCM_API_Setting _, bool Value)
{
	`TRACE_ENTRY("");
	MIN_FORCE_LEVEL_PAUSE_MCMUI.SetEditable(Value);
	`TRACE_EXIT("");
}

simulated function ClientModCallback(MCM_API_Instance ConfigAPI, int GameMode)
{
	local MCM_API_SettingsPage Page;
	local MCM_API_SettingsGroup GeneralGroup, RegionGroup;

	local XComGameStateHistory History;
	local XComGameState_WorldRegion Region;
	local int RegionIndex;

	`TRACE_ENTRY("");

	LoadSavedSettings();

	Page = ConfigAPI.NewSettingsPage(sModName);
	Page.SetPageTitle(sModName @ class'Version'.static.GetVersionStringWithPrefix());
	Page.SetSaveHandler(SaveButtonClicked);
	Page.EnableResetButton(ResetButtonClicked);

	GeneralGroup = Page.AddGroup('GeneralGroup', sGeneralSettings_MCMText);
	`MCM_API_AutoAddCheckBox(GeneralGroup, NOTIFY_ADVENT_STRENGTH, none);
	`MCM_API_AutoAddCheckBox(GeneralGroup, NOTIFY_FORCE_LEVEL, );
	`MCM_API_AutoAddCheckBox(GeneralGroup, PAUSE_ADVENT_STRENGTH, PauseAdventStrengthChangeHandler);
	`MCM_API_AutoAddCheckBox(GeneralGroup, PAUSE_FORCE_LEVEL, PauseForceLevelChangeHandler);
	`MCM_API_AutoAddSLider(GeneralGroup, MIN_ADVENT_STRENGTH_PAUSE, 1, 20, 1, );
	`MCM_API_AutoAddSLider(GeneralGroup, MIN_FORCE_LEVEL_PAUSE, 1, 20, 1, );

	RegionGroup = Page.AddGroup('RegionGroup', sRegionalSettings_MCMText);

	History = `XCOMHISTORY;

	foreach History.IterateByClassType(class'XComGameState_WorldRegion', Region)
	{
		if (!Region.HaveMadeContact()) continue;

		RegionIndex = class'WorldRegionLib'.static.GetRegionIndex(Region);

		switch (RegionIndex)
		{
			case 0:
				ADVENT_STRENGTH_PAUSE_REGION_0_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_0, );
				break;
			case 1:
				ADVENT_STRENGTH_PAUSE_REGION_1_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_1, );
				break;
			case 2:
				ADVENT_STRENGTH_PAUSE_REGION_2_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_2, );
				break;
			case 3:
				ADVENT_STRENGTH_PAUSE_REGION_3_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_3, );
				break;
			case 4:
				ADVENT_STRENGTH_PAUSE_REGION_4_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_4, );
				break;
			case 5:
				ADVENT_STRENGTH_PAUSE_REGION_5_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_5, );
				break;
			case 6:
				ADVENT_STRENGTH_PAUSE_REGION_6_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_6, );
				break;
			case 7:
				ADVENT_STRENGTH_PAUSE_REGION_7_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_7, );
				break;
			case 8:
				ADVENT_STRENGTH_PAUSE_REGION_8_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_8, );
				break;
			case 9:
				ADVENT_STRENGTH_PAUSE_REGION_9_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_9, );
				break;
			case 10:
				ADVENT_STRENGTH_PAUSE_REGION_10_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_10, );
				break;
			case 11:
				ADVENT_STRENGTH_PAUSE_REGION_11_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_11, );
				break;
			case 12:
				ADVENT_STRENGTH_PAUSE_REGION_12_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_12, );
				break;
			case 13:
				ADVENT_STRENGTH_PAUSE_REGION_13_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_13, );
				break;
			case 14:
				ADVENT_STRENGTH_PAUSE_REGION_14_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_14, );
				break;
			case 15:
				ADVENT_STRENGTH_PAUSE_REGION_15_Label = Region.GetDisplayName();
				`MCM_API_AutoAddCheckBox(RegionGroup, ADVENT_STRENGTH_PAUSE_REGION_15, );
				break;
		}
	}

	Page.ShowSettings();

	`TRACE_EXIT("");
}

simulated function LoadSavedSettings()
{
	`TRACE_ENTRY("");

	NOTIFY_ADVENT_STRENGTH = `GETMCMVAR(NOTIFY_ADVENT_STRENGTH);
	NOTIFY_FORCE_LEVEL = `GETMCMVAR(NOTIFY_FORCE_LEVEL);
	PAUSE_ADVENT_STRENGTH = `GETMCMVAR(PAUSE_ADVENT_STRENGTH);
	PAUSE_FORCE_LEVEL = `GETMCMVAR(PAUSE_FORCE_LEVEL);
	MIN_ADVENT_STRENGTH_PAUSE = `GETMCMVAR(MIN_ADVENT_STRENGTH_PAUSE);
	MIN_FORCE_LEVEL_PAUSE = `GETMCMVAR(MIN_FORCE_LEVEL_PAUSE);

	ADVENT_STRENGTH_PAUSE_REGION_0 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_0);
	ADVENT_STRENGTH_PAUSE_REGION_1 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_1);
	ADVENT_STRENGTH_PAUSE_REGION_2 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_2);
	ADVENT_STRENGTH_PAUSE_REGION_3 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_3);
	ADVENT_STRENGTH_PAUSE_REGION_4 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_4);
	ADVENT_STRENGTH_PAUSE_REGION_5 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_5);
	ADVENT_STRENGTH_PAUSE_REGION_6 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_6);
	ADVENT_STRENGTH_PAUSE_REGION_7 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_7);
	ADVENT_STRENGTH_PAUSE_REGION_8 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_8);
	ADVENT_STRENGTH_PAUSE_REGION_9 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_9);
	ADVENT_STRENGTH_PAUSE_REGION_10 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_10);
	ADVENT_STRENGTH_PAUSE_REGION_11 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_11);
	ADVENT_STRENGTH_PAUSE_REGION_12 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_12);
	ADVENT_STRENGTH_PAUSE_REGION_13 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_13);
	ADVENT_STRENGTH_PAUSE_REGION_14 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_14);
	ADVENT_STRENGTH_PAUSE_REGION_15 = `GETMCMVAR(ADVENT_STRENGTH_PAUSE_REGION_15);

	`TRACE_EXIT("");
}

/**
 * Resets all MCM settings to their default values.
 *
 * @param Page The settings page being reset.
 */
simulated function ResetButtonClicked(MCM_API_SettingsPage Page)
{
	`TRACE_ENTRY("");

	`MCM_API_AutoReset(NOTIFY_ADVENT_STRENGTH);
	`MCM_API_AutoReset(NOTIFY_FORCE_LEVEL);
	`MCM_API_AutoReset(PAUSE_ADVENT_STRENGTH);
	`MCM_API_AutoReset(PAUSE_FORCE_LEVEL);
	`MCM_API_AutoReset(MIN_ADVENT_STRENGTH_PAUSE);
	`MCM_API_AutoReset(MIN_FORCE_LEVEL_PAUSE);

	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_0);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_1);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_2);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_3);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_4);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_5);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_6);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_7);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_8);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_9);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_10);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_11);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_12);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_13);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_14);
	`MCM_API_AutoReset(ADVENT_STRENGTH_PAUSE_REGION_15);

	`TRACE_EXIT("");
}

/**
 * Saves current MCM settings and applies them to the active Tactical HUD.
 *
 * @param Page The settings page being saved.
 */
simulated function SaveButtonClicked(MCM_API_SettingsPage Page)
{
	`TRACE_ENTRY("");

	self.CONFIG_VERSION = `MCM_CH_GetCompositeVersion();
	self.SaveConfig();

	`TRACE_EXIT("");
}